version: '2'
services:
  oauth2_proxy:
    image: oauth2_proxy
    ports:
      - "4180:4180"
    networks:
      - nginx-auth
    volumes:
      - ./oauth2_proxy/config:/config
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - nginx-auth
  nginx:
    build: .
    environment:
      - JWT_SECRET=secret
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/opt/openresty/nginx/conf
      - ./scripts:/opt/openresty/nginx/scripts
    networks:
      - nginx-auth
    depends_on:
      - oauth2_proxy
      - redis
networks:
  nginx-auth:
